[package]
name = "raytracing_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.5.3"
log = "0.4.0"
env_logger = "0.9.0"
ansi_term = "0.12.1"